main.go

Hi @ngwese,
I did some tidying of the Go code in maiden.
I hope you do not find this inappropriate.
I think that these small changes are easy wins.
There is more I could do, and would like to do, if this pleases you.
Cheers,
@nf

Some Go cleanups

---

main.go

This can be used in concert with a systemd config to have maiden
listen on port 80 by default.
Issue #92.

Add -fd flag to pass a file descriptor on which to serve HTTP

---

app/src/model/repl-reducers.js
app/src/repl.css

possibly a naive fix, but tabs at least look good.
let me know if i'm missing anything or if there's a better approach.
fixes #6 
/cc @ngwese

repl output whitespace formatting

---

app/src/repl.css

a stab at some repl input styling.
fixes: #99 
/cc @ngwese @tehn

repl input label styling

---

docs/keybindings.md

the start of some notes on keybindings.  in the long run a pdf or integration into a maiden one-sheet would be nice but something like this should be useful in the interim.
@ngwese, @tehn: comments about format and approach very welcome
also, happy to highlight more useful editor shortcuts.  chime in with your favorites! :)

keybindings doc (wip)

---

README.md
app/README.md

this pr includes info about the versions of various toolchain components known to work as well as documenting the `repl-endpoints.json` file and typical dev setup.
/cc @pq

add detail on tool version and dev setup

---

docs/keybindings.md

add indent, outdent, and completions

---

app/src/editor.css
app/src/editor.js
app/src/services.js
app/src/snippets.js

snippet plumbing and basic norns script snippets
* adds hooks to contribute completers to the ace editor 
* defines a new service that associates completers w/ file types
* introduces a `nornsSnippetCompleter` that adds snippets for `norns` script functions
* tweaks completion CSS to be more consistent w/ overall LAF
in action (completions are triggered w/ `CTRL+SPACE`):
more snippets, completions, styling to come; needless to say, ideas and word-smithing greatly welcome!
/cc @ngwese

snippet plumbing and basic norns script snippets

---

app/src/repl.js

de-smart links

---

app/src/mode.js
app/src/mode/lua.js
app/src/services.js

tidying to separate concerns.  substantially, moves lua mode logic from `services` to the lua mode proper.
/cc @ngwese

lua mode tidying

---

app/src/editor.css

update tooltip css.
fixes: #126 
/cc @ngwese

dark mode gutter hover styling (#126)

---

app/README.md

fix typo in dev server start instructions 

---

.gitignore
app/package.json
app/src/api.js
app/src/bound-edit-activity.js
app/src/bound-workspace.js
app/src/constants.js
app/src/edit-activity.js
app/src/explorer.css
app/src/explorer.js
app/src/modal-get-name.js
app/src/workspace.js
main.go
release.sh

changes to support norns 2.0, specifically mods to support new dust structure:
- single tree view for new
- filter out "dot" files/dirs in maiden backend
- update play button logic to work w/ new dust structure

single tree view for new dust structure

---

web/src/edit-activity.js
web/src/model/ui-reducers.js

Fixes the first part of #168. Second part to follow when I've come up with a good way to make it configurable.
cc @ngwese

Dock REPL to bottom of browser window on resize

---

.gitignore
tool/project-setup.sh
tool/release.sh
web/src/activities.js
web/src/activity-bar.js
web/src/bound-project-activity.js
web/src/components/catalog.js
web/src/components/project-info.css
web/src/components/project-info.js
web/src/components/project-list.js
web/src/help-button.js
web/src/modal-content.js
web/src/modal-get-name.js
web/src/modal-progress.js
web/src/model/project-actions.js
web/src/model/project-reducers.js
web/src/project-activity.js
web/src/repl.js

Adds several modal dialogs to provide more positive indication that work is being done on the device. The UI is not the most elegant (and could use some refinement) but it is complete enough to be usable.
Resolves #137 
/cc @ryanlaws

Polish up some the project management bits

---

tool/project-setup.sh

making sure people don't get confused during (manual) updates
see [this post](https://llllllll.co/t/norns-file-structure-update-question/35859)

guard against alarming error message

---

web/public/repl-endpoints.json
web/public/units.json

iirc this was a request from some months back. took a second look and it was trivial

sc -> supercollider in repl

---

.github/workflows/build-release.yaml
web/gen-version.sh

...why not give maiden the automated build treatment as well.

automate release builds

---

web/src/bound-edit-activity.js
web/src/edit-activity.js
web/src/svg-icons.js

provide script stop/clear button

---

web/src/bound-workspace.js
web/src/explorer.js
web/src/model/edit-actions.js
web/src/model/edit-reducers.js

- creating files requires selecting a location first
- implicit files are created under dust/code
fixes: #160

improve implicit untitled.lua creation handling

---

web/src/repl.js

disable mobile browser autocorrect in repl
