app/src/editor.js

snippets and completions are invoked w/ **⌘.**  (or non-mac: **ctrl+.**).
i’d like to experiment with some custom snippets and completions but the basics already add value IMO.  down the road we could consider enabling live completion (e.g., not behind **⌘.**) but that’s disruptive enough that it should be opted-in via an editor config.
/cc @ngwese

lua snippet and basic auto complete support

---

app/package.json
app/src/repl.js
app/yarn.lock

linkifies repl outputs
note the use of the `_blank` target property to ensure we open in a fresh tab/page.  we'll want to be smarter about when to do that when we support routing #70.
/cc @ngwese @anthonybarsotti

linkify repl output

---

app/src/editor.js
app/src/mode/lua.js
app/src/services.js
app/src/snippets.js

* introduces a new lua editor mode that extends the default, swapped in on-render
* rejiggers mode selection and introduces an `editorService`
* fixes over-contribution of norns completions (enabling non-duplicated results w/ no prefix)
* prunes removed/deprecated lúa keywords (notably these were presented in auto-completions)
see: #78
/cc @ngwese 
/fyi @anthonybarsotti @jlmitch5 
(_replaces #116, which i borked on rebase_)

norns lua mode / editing improvements

---

app/src/configure-activity.js
app/src/editor.css
app/src/editor.js
app/src/model/config-reducers.js
app/src/services.js
app/src/theme/norns_dark.js

norns dark editor mode 
* 🕶  introduces a new norns dark mode editor theme (“norns_dark”), based on “tomorrow night” (w/ error style borrowed from “chaos”); refinements tracked in #122
* 🕶  adds dark mode aware styling of completion and documentation pop-ups
* 🕶  adds a new editor config to toggle modes (light / “dawn” remains default)
* 🎆  **anti-aliases all text** (where supported; sorry windows ☹️ )
a few visuals.
anti-aliasing and error marking:
dark mode popup styling:
editor config:
whole enchilada:
fixes: #33 
@jlmitch5: i **_think_** i wired up the config stuff right but would love confirmation
/cc @ngwese @simonvanderveldt

dark editor mode 😎 

---

app/src/editor.js
app/src/mode.js
app/src/services.js

disable default (not-working) snippets for text mode.
fixes: #129 
/cc @ngwese

disable default (not-working) snippets for text mode (#129)

---

app/README.md

I don't believe there is any need for a globally installed `react-scripts`.
Also updated the instructions for installing `node` and `yarn`.

Update app/README.md to remove react-scripts

---

web/src/bound-edit-activity.js
web/src/edit-activity.js
web/src/editor.js
web/src/services.js

simple feature to allow the current selection in the editor to be sent to the repl for evaluation.

add ctl/cmd-8 keybinding to eval selection

---

web/src/editor.js

This seems to improve matters when re-eval-ing functions and I tried it on some multi-expression selections.  Let me know if there are other cases where this breaks and thanks for adding the feature.

improve multi-line eval

---

web/src/repl-activity.css

before:
after:
Pretty minor change, but I think it does the job. Made sure to use a shade of gray that's used elsewhere in the styles.

Highlight selected REPL tab more prominently (fixes #90)

---

web/src/repl.js

Picking more low-hanging fruit; apparently MS [didn't bother to implement](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo) element.scrollTo(), but setting scrollTop is a viable alternative.

Fix `scrollTo` error in MS Edge (fixes #157)

---

web/src/modal-get-name.js
web/src/model/edit-reducers.js

Thought I'd take a stab at #113 too. In the process, I noticed a couple other things:
- `getSiblingNamesForResource` returns the specified resource's name, in addition to those of its siblings, so users would get a "name already in use" error if they clicked Rename and then OK without making any changes. That felt weird to me, so I worked around it. Not sure if I did so in the best possible way (perhaps getSiblingNames... should be modified instead, but I was daunted by all the immutable.js stuff).
- After renaming a file, the explorer's `activeNode` becomes undefined, so if you click the rename button again, nothing happens. I feel pretty confident that I fixed this in the Correct Way, but I'd welcome any corrections!

File rename modal polish

---

web/src/edit-activity.js
web/src/editor.js
web/src/services.js

This fixes `CTRL+P` in the editor for "playing" the current script (fix #71). I tested it for the default Ace keybindings and for the Vim ones. The existing keybindings applied to the window, but were overridden by the Ace editor and it appears that their default/lower-precedence behaviors were prevented.
The significant change is twofold. First, the relevant `activeBuffer` and `scriptRun()` props are passed from `EditActivity` to its `Editor`. The former had to be aliased to `activityActiveBuffer` due to conflicts surfaced in testing. This is then wrapped in a `getActiveBuffer()` helper in `render()` to ensure freshness. Next, a `commands` prop is passed to said `Editor`, which is an array of commands associated with keys. The sole member of `commands` is a mapping of `CTRL+P` to a call …

Fix CTRL+P in editor

---

web/src/api.js
web/src/bound-project-activity.js
web/src/components/catalog-list.js
web/src/components/catalog.css
web/src/components/catalog.js
web/src/components/project-list.css
web/src/components/project-list.js
web/src/components/text-button.js
web/src/modal-content.css
web/src/modal-content.js
web/src/model/project-actions.js
web/src/project-activity.js

fixes https://github.com/monome/maiden/issues/175
DONE
on the available packages list, change the install button to non-clickable, installed grey text
---
on the installed packages list, have an "update all" button at the top, which only has a single confirmation dialog after clicking "update all", then recursively goes through each installed package and tries to update.
This last modal will change the header to succeeded if no projects fail.  If a combination of succeeded and failed updates happen it should show the succeeded projects in a list, then the failed ones in a list (with the reason, like shown in the screenshot above).

Project ux enhancements

---

web/src/help-button.css
web/src/help-button.js

Fixes #174 
Addresses issue of both low opacity and contrast on the help popup and text.
Moves popup library styling within css. Reluctantly had to use `!important` to do so - I understand if this isn't the ideal solution here

Fix - low contrast on help menu

---

cmd/project.go

This patch fixes a confusing help message (most likely due to copy & paste).

help message fix

---

cmd/catalog_update.go
cmd/server.go
web/src/bound-project-activity.js
web/src/components/catalog-list.css
web/src/components/catalog-list.js
web/src/components/project-list.css
web/src/model/project-actions.js
web/src/project-activity.js

- adds automatic refresh on device startup
- adds giant refresh all button at top of the `available` (aka catalog) view which fetches updates to all the catalogs
given the way the catalog stuff works internally these changes fall short of delivering the desired user experience. specifically:
- the completion dialog for the refresh all catalog action only lists the catalogs which were updated but it doesn't give any indication if there were new entries or not
- catalogs which fail to update will be reported as having been updated _if the catalog was downloaded previously_. update failures are only shown if the catalog does not exist on the device
fixes: #184

catalog refresh

---

web/package.json
web/src/editor.js
web/src/mode/lua.js
web/src/theme/norns_dark.js
web/yarn.lock

- upgrades to latest react-ace builds, which:
- fixes indention of `end` keywords
- not longer flags `<<` and `>>` as syntax errors in lua mode
in addition this enables soft line wrapping on the editor
fixes: #9

upgrades react-ace to latest version

---

web/src/model/repl-reducers.js

the recent change renaming the `sc` repl to the `supercollider`
repl broke logic which was conditioned on the name of the repl
fixes: #198

restore special handling of line endings for supercollider repl

---

web/src/editor.js
web/src/services.js

this PR pulls in an idea from SuperCollider: that Ctl+Enter will evaluate the current line or the current selection. to do this I made two changes:
- Ctl+Enter is valid key-binding to do a `eval`
- the `eval` will evaluate the current line if nothing is selected
why? this PR makes maiden easier to use as a live coding environment. I've started using [maiden as a live-coding environment](https://github.com/schollz/nornsdeck) but currently I'm doing this with vim with special bindings+utilities to send lines to maiden. however, I thought if I were to make this available to other people it would be great to have the "send current line" functionality available in maiden, which is much easier to use than vim. 
of course, feel free to completely ignore this PR for any reason :)

eval evaluates current line if nothing selected + Ctl-Enter evals

---

web/package.json
web/src/edit-activity.css
web/src/edit-activity.js
web/src/model/edit-helpers.js
web/yarn.lock

This leverages `react-audio-player` and some very basic logic to play a file with an `audio/*` MIME type instead of showing the editor. This would address #83, I believe (in its original intent, not the upload/download idea).
However, it takes a moment to load the file, and during that time still displays the editor. That's a little confusing, but I know nothing about React so I'm not sure where to fix that. If somebody could give me a pointer, I'd be happy to add that to this PR.

Play audio files in maiden

---

Makefile
cmd/server.go
cmd/version.go
tool/release.sh

The version reported by `./maiden version` is currently incorrect on a clean build. This PR adjusts the build to inject the current tag / build timestamp into the binary.
Before I committed these changes there was a top-level tag and the new version looks like this:
```
~$ make && ./maiden version
go build -ldflags="-X github.com/monome/maiden/cmd.version=v1.1.3 -X github.com/monome/maiden/cmd.compileTime=2021-09-10T13:25"
v1.1.3 / 2021-09-10T13:25
~$ go build && ./maiden version
development
```
After my commit, there is no top-level tag so a hash is included:
```
~$ make && ./maiden version
go build -ldflags="-X github.com/monome/maiden/cmd.version=v1.1.3-1-gbf56356 -X github.com/monome/maiden/cmd.compileTime=2021-09-10T13:27"
v1.1.3-1-gbf56356 / 2021-09-10T13:27
```

Add version metadata during build.

---

Makefile
tool/release.sh

Adds option for building a release for the current architecture with `make release-local`.
This option would allow me to use the `project-setup.sh` script while installing maiden/matron in a docker container.

Allow release script to run on any architecture.
